[package]
name = "innocence-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { version = "4.0.0", features = ["verify"] }
alloy-sol-types = { workspace = true }
sha2 = "0.10"
hex-literal = "0.4"

[[bin]]
name = "innocence-proof"
path = "src/main.rs"